### ISSUE TITLE
ImageGrab not on Linux

### ISSUE THREAD

**Issue by atzengin** [natdebru/OpenCV-Video-Label#1]
ImageGrab won't come in PIL as in Windows. Instead, pyscreenshot can be used. Please consider adding a platform option.

**Comment by natdebru** [comment]
Do you know whether mss works? ImageGrab was actually the old way I used to do screen capturing, changed it to mss because it is faster, but I forgot to replace it at one place in the code.

**Comment by atzengin** [comment]
Haven't tried mss but tried the following and it works on Linux.

`import pyscreenshot as ImageGrab`

**Comment by natdebru** [comment]
After adding that import screen capturing  worked? In that case mss should be working and I can just replace that line with mss, otherwise I will add that import.

**Comment by atzengin** [comment]
```
from PIL import Image, ImageTk
import pyscreenshot as ImageGrab
```
this works fine as I tried. Not sure if it works on Windows. 

I'll report another issue related with mouse scrolling too.

**Comment by natdebru** [comment]
Thank you, hope it is fixed now.
