### ISSUE TITLE
MouseScroll on Linux

### ISSUE THREAD

**Issue by atzengin** [natdebru/OpenCV-Video-Label#2]
I forgot to thank you for this wonderful tool. Thanks a lot. It's quite useful. I want it to better so want to contribute a little bit.

Since the handling of mouse button on Linux is slightly different than on Windows, there is a problem with scrolling on the dataset frame.

Binding must be like this:
```
self.canvas.bind_all("<Button-4>", self._on_mousewheel)
self.canvas.bind_all("<Button-5>", self._on_mousewheel)
```
And the handler must be like this:

```
if event.num == 4:
            self.canvas.yview_scroll(-1, "units")
elif event.num == 5:
            self.canvas.yview_scroll(1, "units")
```

These are only for Linux though. So there must be an OS-aware structure. [http://code.activestate.com/recipes/578894-mousewheel-binding-to-scrolling-area-tkinter-multi/](url) this link would help.

**Comment by natdebru** [comment]
Thank you too for finding bugs. I will look into this.
