### ISSUE TITLE
ICON on Linux

### ISSUE THREAD

**Issue by atzengin** [natdebru/OpenCV-Video-Label#3]
Hi again. Another day, another issue.

I already have a workaround for this but it might be better if fixed.
ICO files are not compatible with tkinter on Linux.
So it throws this error:

>  $ python __main__.py
> Traceback (most recent call last):
>   File "__main__.py", line 300, in <module>
>     app = MainWindow()
>   File "__main__.py", line 58, in __init__
>     self.root.wm_iconbitmap(ICON)
>   File "/usr/lib64/python3.6/tkinter/__init__.py", line 1868, in wm_iconbitmap
>     return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
> _tkinter.TclError: bitmap "bitmaps/icon.ico" not defined

My workaround is to create a png version of icon.ico as icon.png.
Then wherever it's needed:

```
        self.icon = tk.PhotoImage(file=ICONPNG)
        self.root.tk.call('wm', 'iconphoto',self.root._w, self.icon)
        # self.root.wm_iconbitmap(ICON)
```
As you already have an OS-aware code, you might do this automatically.
I don't know if it's possible to use PNG as icon on Windows.
If it does, then there would only be one icon file which is icon.png.

**Comment by natdebru** [comment]
Yes, thank you. This should work on both Windows and Linux. 
[https://stackoverflow.com/questions/48981184/set-window-icon-tkinter-macosx?rq=1](url) seems to suggest that there is no clean way of adding icons on Mac OS.
