### ISSUE TITLE
Requirement missing

### ISSUE THREAD

**Issue by atzengin** [natdebru/OpenCV-Video-Label#4]
I believe this should be in the requirements.txt.
Not sure which version though.

> requests

**Comment by atzengin** [comment]
This one shouldn't be closed I think.
'requests' is still a dependency to be met.

> $ python __main__.py
> Traceback (most recent call last):
>   File "__main__.py", line 300, in <module>
>     app = MainWindow()
>   File "__main__.py", line 62, in __init__
>     self.load_trackers()
>   File "__main__.py", line 137, in load_trackers
>     from algorithms.re3 import re3_tracker
>   File "/home/tarik/Programs/OpenCV-Video-Label/algorithms/re3/re3_tracker.py", line 12, in <module>
>     from .model_downloader import download_re3_model
>   File "/home/tarik/Programs/OpenCV-Video-Label/algorithms/re3/model_downloader.py", line 1, in <module>
>     from google_drive_downloader import GoogleDriveDownloader as gdd
>   File "/home/tarik/Programs/OpenCV-Video-Label/venv/lib/python3.6/site-packages/google_drive_downloader/__init__.py", line 1, in <module>
>     from .google_drive_downloader import GoogleDriveDownloader
>   File "/home/tarik/Programs/OpenCV-Video-Label/venv/lib/python3.6/site-packages/google_drive_downloader/google_drive_downloader.py", line 2, in <module>
>     import requests
> ModuleNotFoundError: No module named 'requests'
>

**Comment by natdebru** [comment]
You are absolutely right, as this was a requirement for GoogleDriveDownloader I had missed it, thanks again!

**Comment by pkr97** [comment]
I'm having the very same issue. how to solve this?
any steps to follow? I followed this link https://gitlab.com/danielgordon10/re3-tensorflow

This is the error what I get.

Traceback (most recent call last):
  File "./demo/image_demo.py", line 9, in <module>
    from tracker import re3_tracker
  File "/home/pkumars/re3-tensorflow-master/tracker/re3_tracker.py", line 12, in <module>
    from re3 import network
ModuleNotFoundError: No module named 're3'

Any help would make my life easier.
