### ISSUE TITLE
Multiple objects detection on video

### ISSUE THREAD

**Issue by momo1986** [natdebru/OpenCV-Video-Label#6]
Hello, 
how can I detect multiple objects?
![image](https://user-images.githubusercontent.com/34225874/57211058-833bcc80-7011-11e9-9ff8-4bf9e223c4ff.png)
Looks like it can only select one box for one object.
Thanks

**Comment by natdebru** [comment]
As of now multiple object tracking is not supported. I might try to implement it later.
